# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'func1_page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 375)
        Form.setStyleSheet("border-image: url(:/images/Qtdesigner/images/1.jpg);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{border-image: url();\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_2 = LineEdit(Form)
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit = LineEdit(Form)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = PushButton(Form)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "△G(solv)预测"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "请输入溶质smiles"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入溶剂smiles"))
        self.pushButton.setText(_translate("Form", "预测"))
from qfluentwidgets import LineEdit, PushButton
import qrc_rc
